
spring:
  data:
    cassandra:
      cluster-name: "manuel_cassandra"
      keyspace-name: "manuel"
  profiles:
    active: "docker_local"

---
spring:
  profiles: "docker_local"
  data:
    cassandra:
      contact-points: "localhost"

---
spring:
  profiles: "docker_machine"
  data:
    cassandra:
      contact-points: "192.168.99.100"
#      contact-points: "127.0.0.1"
      port: 9042

