spring:
  data:
    cassandra:
      cluster-name: "manuel_cassandra"
      keyspace-name: "manuel"

---
spring:
  profiles: "docker_local"

  data:
    cassandra:
      contact-points: "localhost"

---
spring:
  profiles: "docker_machine"
  data:
    cassandra:
      contact-points: "192.168.99.100"

