version: '2'

services:
  cassandra:
    image: 'cassandra:3.7'
    container_name: 'cassandra_dev'
    volumes: 
      - '/Users/rnkoaa/cassandra-data/:/var/lib/cassandra'
    ports: 
      - '127.0.0.1:9042:9042'
      - '127.0.0.1:9160:9160'
    environment: 
      - 'm=2g'
#    networks:
#      - "cassandra_network"

#networks:
#  cassandra_network:
#    driver: bridge
